version: '3'

services:
  strange:
    build:
      context: .
      dockerfile: strange-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3333:3333"
    environment:
      dbType: "postgres"
      DSN: "host=postgres port=5431 user=postgres password=password dbname=strange sslmode=disable timezone=UTC connect_timeout=5"
      dbURL: "postgres://postgres:password@postgres:5431/strange?sslmode=disable"
      migrationPath: "file:///app"

  postgres:
    image: 'postgres:14.2-alpine'
    ports:
      - "5431:5431"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strange
#    volumes:
#      - ./db-data/postgres/:/var/lib/postgresql/data/