basePath: /api/v1/
definitions:
  handlers.jsonResponse:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
  handlers.requestPayload:
    properties:
      date_from:
        type: string
      date_to:
        type: string
      description:
        type: string
      name:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:3333
info:
  contact: {}
  title: strange API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Get the root endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.jsonResponse'
      summary: Get root endpoint
      tags:
      - Root
  /schedule/day:
    get:
      consumes:
      - application/json
      description: Get meets for day
      parameters:
      - description: Date of the day (YYYY-MM-DD)
        in: query
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful assignment
          schema:
            $ref: '#/definitions/handlers.jsonResponse'
        "400":
          description: Invalid date format
          schema:
            $ref: '#/definitions/handlers.jsonResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.jsonResponse'
      summary: Get meets for day
      tags:
      - Schedule
  /schedule/reserve:
    post:
      consumes:
      - application/json
      description: Assign meet for the day
      parameters:
      - description: Request payload
        in: body
        name: requestPayload
        required: true
        schema:
          $ref: '#/definitions/handlers.requestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Successful assignment
          schema:
            $ref: '#/definitions/handlers.jsonResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.jsonResponse'
      summary: Assign meet for the day
      tags:
      - Schedule
swagger: "2.0"
